# Generated by Django 2.2.11 on 2020-03-26 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputImage', models.ImageField(upload_to='pics')),
                ('pic', models.FileField(upload_to='pics')),
            ],
        ),
    ]
